# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title disj
#'
#' @description
#'  disjunctive
#'
#' @param strata vector of integer
#'
#' @return vector
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
disj <- function(strata) {
    .Call(`_fastcube_disj`, strata)
}

#' @title ncat
#'
#' @description
#' number of cat in each column
#'
#' @param Xcat Matrix
#'
#' @return vector
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
ncat <- function(Xcat) {
    .Call(`_fastcube_ncat`, Xcat)
}

#' @title disjMatrix
#'
#' @description
#' disj on each column
#'
#' @param starta a Matrix
#'
#' @return a matrix
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
disjMatrix <- function(strata) {
    .Call(`_fastcube_disjMatrix`, strata)
}

#' @title is Identiy matrix
#'
#' @param M matrix
#'
#' @return bool
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
isEye <- function(M) {
    .Call(`_fastcube_isEye`, M)
}

#' @title reduced row echelon form arma implementation
#'
#'
#' @param M matrix
#'
#' @return NULL (transform matrix)
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
rrefArma <- function(M) {
    invisible(.Call(`_fastcube_rrefArma`, M))
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param prob inclusion probabilities
#' @param Bm matrix of auxiliary variables
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
osffphase <- function(prob, Bm) {
    .Call(`_fastcube_osffphase`, prob, Bm)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param B matrix of auxiliary variables.
#' @param pik vector of inclusion probabilities
#' @param EPS tolerance
#'
#' @return updated pik
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
onestep <- function(B, pik, EPS = 0.0000001) {
    .Call(`_fastcube_onestep`, B, pik, EPS)
}

#' @title title
#'
#'
#'
#' @param X matrix of auxiliary variables.
#' @param pik vector of inclusion probabilities
#' @param EPS tolerance
#'
#' @return a sample
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
flightphase_arma <- function(X, pik, redux) {
    .Call(`_fastcube_flightphase_arma`, X, pik, redux)
}

#' @title Reduction of the matrix
#'
#' @description
#'
#' This function reduces the size of the matrix by removing alternatively columns and rows that have sum equal to 0.
#'
#' In case where the number of auxiliary varibale is great (p very large), even if we use the fast implementation proposed by
#' (Chauvet and Tillé 2005) the problem is time consuming. If we have the chance that the matrix is strongly sparse,
#' we can then use the function to reduce the size of the matrix B by using this method.
#'
#' If the matrix is dense or every column have sum greater than 0, then nothing is changed.
#'
#' @param B a matrix of size (p+1 x p) sub-matrix of auxiliary matrix.
#'
#' @return a list
#'
#' @references
#' Chauvet, G. and Tillé, Y. (2006). A fast algorithm of balanced sampling. Computational Statistics, 21/1:53–62.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#'
#' @export
reduxArma <- function(B) {
    .Call(`_fastcube_reduxArma`, B)
}

#' @encoding UTF-8
#' @title systematic desgin
#'
#' @description
#'
#' Find all possible systematic sample from a vector of inclusion probabilities \code{pik}.
#'
#' @param pik vector of inclusion probabilities..
#'
#' @return A matrix of size at most N x N with elements equal to 0 or 1. The value 1 indicates that the uni is selected while the value 0 is for non-chosen unit.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#' @export
systematicDesign <- function(pik) {
    .Call(`_fastcube_systematicDesign`, pik)
}

