# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
chooseRec <- function(n, k) {
    .Call(`_fastcube_chooseRec`, n, k)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
choose <- function(n, k) {
    .Call(`_fastcube_choose`, n, k)
}

#' @title disjunctive vector
#'
#' @description
#' This function transform a categorical variable into a matrix of indicators.
#'
#' @param strata A vector of integer that represents the category.
#'
#' @return A matrix of indicators.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @examples
#'   strata <- rep(c(1,2,3),each = 4)
#'   disj(strata)
#'
#' @export
disj <- function(strata) {
    .Call(`_fastcube_disj`, strata)
}

#' @title number of category
#'
#' @description
#' This function returns the number of factor in each column of a categorical matrix.
#'
#' @param Xcat A matrix of integer that contains categorical variable in column.
#'
#' @return A row vector that contains the number of category in each column.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
ncat <- function(Xcat) {
    .Call(`_fastcube_ncat`, Xcat)
}

#' @title disjunctive Matrix
#'
#' @description
#' This function transform a categorical matrix into a matrix of indicators variables.
#'
#' @param A matrix of integer that contains categorical variable in column.
#'
#' @return A matrix of indicators.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
disjMatrix <- function(strata) {
    .Call(`_fastcube_disjMatrix`, strata)
}

#' @title findBarma
#'
#' @description
#' findB
#'
#' @param X a Matrix
#' @param Xcat a Matrix
#'
#' @return a matrix
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
findBarma <- function(X, Xcat) {
    .Call(`_fastcube_findBarma`, X, Xcat)
}

#' @title title
#'
#' @description
#' description Rosetta code combn
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
samplen <- function(N, n) {
    .Call(`_fastcube_samplen`, N, n)
}

#' @encoding UTF-8
#' @title systematic desgin
#'
#' @description
#'
#' Find all possible systematic sample from a vector of inclusion probabilities \code{pik}.
#'
#' @param pik vector of inclusion probabilities..
#'
#' @return A matrix of size at most N x N with elements equal to 0 or 1. The value 1 indicates that the uni is selected while the value 0 is for non-chosen unit.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#' @export
systematicDesign <- function(pik) {
    .Call(`_fastcube_systematicDesign`, pik)
}

